Fix flaky JobMasterIntegrationTest
**What changes are proposed in this pull request?**
Fix flaky JobMasterIntegrationTest, add more log info to guard future
test flaky

**Why are the changes needed?**
This integration test uses small `JOB_MASTER_WORKER_HEARTBEAT_INTERVAL`,
`JOB_MASTER_WORKER_TIMEOUT`, and `JOB_MASTER_LOST_WORKER_INTERVAL` to
accelerate the integration test. This setting is totally fine when we do
tests at a local machine or Jenkins. However, the
`JOB_MASTER_WORKER_HEARTBEAT_INTERVAL` can take a much longer time in
GitHub action, which results in a list of flaky tests. The error message
is as follows:

```
Error: 3.474 [ERROR]
alluxio.job.master.JobMasterIntegrationTest.throttleJobWorkerTasks Time
elapsed: 32.855 s <<< ERROR!
java.util.concurrent.TimeoutException: Timed out waiting for job
1643913746839 to be one of status [RUNNING, COMPLETED] options:
WaitForOptions{interval=20, timeout=30000} last value: false,
PlanInfo{id=1643913746839, errorType=JobWorkerLost, errorMessage=Task
execution failed: Job worker(bbf508a040fc) was lost before the task(0)
could complete, childPlanInfoList=[TaskInfo{jobId=1643913746839,
taskId=0, status=COMPLETED, errorMessage=, result=null,
lastUpdated=1643913737647, workerHost=bbf508a040fc, description=}],
status=FAILED, result=, lastUpdated=1643913737650, name=Sleep,
description=SleepJobConfig{timeMs=1}, affectedPaths=[]}
at alluxio.job.util.JobTestUtils.waitForJobStatus(JobTestUtils.java:80)
at
alluxio.job.master.JobMasterIntegrationTest.throttleJobWorkerTasks(JobMasterIntegrationTest.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at
alluxio.job.plan.PlanDefinitionRegistryRule$1.evaluate(PlanDefinitionRegistryRule.java:49)
at
alluxio.testutils.LocalAlluxioClusterResource$1.evaluate(LocalAlluxioClusterResource.java:198)
at
org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
at
org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:748)
```

This pr change should partially eliminate the test flaky because of job
worker lost.

**Does this PR introduce any user facing changes?**
No

pr-link: Alluxio/alluxio#14959
change-id: cid-d513ec4a2c288d41d4e222594ccf5555a4415dfb