Print worker for loadCommand while cache failed
### What changes are proposed in this pull request?

Add worker to output information while cache failed.

### Why are the changes needed?

From the following output, I cannot identify the failed worker.

```
Failed to complete cache request for block 2484118487040 of file /test:
io.grpc.StatusRuntimeException: UNKNOWN: java.io.IOException: Failed to
read from UFS, sessionId=-8, blockId=2484118487040, offset=0,
positionShort=false, options=ufs_path: "hdfs://ns1/test"
offset_in_file: 0
block_size: 161266153
maxUfsReadConcurrency: 2147483647
mountId: 1381858014512144475
no_cache: false
: com.google.common.util.concurrent.UncheckedExecutionException:
com.google.common.util.concurrent.UncheckedExecutionException:
java.lang.IllegalArgumentException: java.net.UnknownHostException: ns1

/ns1/test loaded
```


### Does this PR introduce any user facing changes?

No

pr-link: Alluxio/alluxio#15541
change-id: cid-08a3d6d211055e3277ca0210287401e3a18c997f