Handle temp directories correctly for multiple test jvm
### What changes are proposed in this pull request?
Change temp dir creation to be unique and delete upon jvm exit.

### Why are the changes needed?
When github runs test with multiple jvms, the two jvms can try to create
temp dir at the same time and cause the following error.

```
Error: 5.534 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0,
Time elapsed: 0.85 s <<< FAILURE! - in
alluxio.client.cli.fsadmin.BackupCommandIntegrationTest
Error: 5.542 [ERROR]
alluxio.client.cli.fsadmin.BackupCommandIntegrationTest Time elapsed:
0.762 s <<< ERROR!
java.lang.ExceptionInInitializerError
at
alluxio.master.AbstractLocalAlluxioCluster.setAlluxioWorkDirectory(AbstractLocalAlluxioCluster.java:362)
at
alluxio.master.LocalAlluxioCluster.initConfiguration(LocalAlluxioCluster.java:128)
at
alluxio.testutils.LocalAlluxioClusterResource.start(LocalAlluxioClusterResource.java:150)
at
alluxio.testutils.LocalAlluxioClusterResource$1.evaluate(LocalAlluxioClusterResource.java:192)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at
org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
at
org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
at
org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
at
org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
at
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at
org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at
org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.RuntimeException: Failed to create testing
directory /tmp/alluxio-tests
at
alluxio.AlluxioTestDirectory.createTestingDirectory(AlluxioTestDirectory.java:80)
at alluxio.AlluxioTestDirectory.<clinit>(AlluxioTestDirectory.java:38)
... 15 more


```

pr-link: Alluxio/alluxio#14901
change-id: cid-55daabed22d736300b244b53e057d94b5a7e1411