Fix load command trigger cache block fail in container env
### What changes are proposed in this pull request?

```Console
$ /opt/alluxio/bin/alluxio fs load /ceph/mbl/testa12.txt
Failed to complete cache request for block 150994944 of file
/ceph/mbl/testa12.txt: io.grpc.StatusRuntimeException: UNKNOWN:
java.io.IOException: Failed to connect to remote block worker:
GrpcServerAddress{HostName=XXX,
SocketAddress=XXX/YYY:29999}/ceph/mbl/testa12.txt loaded
```

### Why are the changes needed?

It is a bug.

### Does this PR introduce any user facing changes?

No

pr-link: Alluxio/alluxio#14272
change-id: cid-5b719989ad7af10c019fdc0d0037a11ac2dbe028