Re-order jars in CLASSPATH to get around conflicting jar corner case
Whenever I went to the Tachyon web UI I would always get the following error:

    HTTP ERROR 500

    Problem accessing /home. Reason:

        Server Error

    Caused by:

    java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.CompilationResult.getProblems()[Lorg/eclipse/jdt/core/compiler/IProblem;
    	at org.apache.jasper.compiler.JDTCompiler$2.acceptResult(JDTCompiler.java:354)
    	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:478)
    	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:425)
    	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:298)
    	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:277)
    	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:265)

    <snip ... etc. etc.>

The problem ended up being that there was an issue with the same class that is included in Hadoop (tried w/ Hadoop 2.4.0 & 2.6.0).  A simple re-ordering of the CLASSPATH setting in libexec/tachyon-config.sh from

export CLASSPATH="$TACHYON_CONF_DIR/:$TACHYON_CLASSPATH:$TACHYON_JAR"

to

export CLASSPATH="$TACHYON_CONF_DIR/:$TACHYON_JAR:$TACHYON_CLASSPATH"

solved this problem.

See https://tachyon.atlassian.net/browse/TACHYON-291 for ticket on longer term solution.