Fix bug of classnotfound at Fuse runtime
### What changes are proposed in this pull request?

fix the bug where fuse has the bug of "java.lang.NoClassDefFoundError: Could not initialize class io.vertx.core.dns.AddressResolverOptions" after jetcd dependency was introduced

### Why are the changes needed?

classes from native side, if not explicitly loaded, it will spew "NoClassDefFoundError" at runtime when the relevant classes was invoked.

### Does this PR introduce any user facing changes?

No.

			pr-link: Alluxio/alluxio#18039
			change-id: cid-999fbcf89cba5d11fded608e0da3e395f6af20c8