[SMALLFIX] Improve rm failure msg
### What changes are proposed in this pull request?

Slightly improve the rm failure msg

### Why are the changes needed?

```
# Before
alluxio.exception.status.FailedPreconditionException: Failed to delete 2
paths: from the under file system/nested/test (Permission denied:
user=userA, access=-w-, path=/nested/test/file: failed at file, inode
owner=test, inode group=, inode mode=rwx------), /nested/test (Directory
not empty)

# After
alluxio.exception.status.FailedPreconditionException: Failed to delete 2
paths from the under file system: /nested/test (Permission denied:
user=userA, access=-w-, path=/nested/test/file: failed at file, inode
owner=test, inode group=, inode mode=rwx------), /nested/test (Directory
not empty)
```

### Does this PR introduce any user facing changes?

NA

pr-link: Alluxio/alluxio#15372
change-id: cid-b1e4274ddf7076ee2d90bd9ee112d6fd866b20af