Add RaftJournalSystem toString
### What changes are proposed in this pull request?

Added `toString` method to RaftJournalSystem
RaftJournalSystem does not have a `toString` method, which can result in
insufficient information for debugging when RaftJournalSystem exceptions
are thrown.

### Why are the changes needed?

```java
AlluxioMasterProcess(JournalSystem journalSystem) {
//....
if (!mJournalSystem.isFormatted()) {
throw new RuntimeException(
String.format("Journal %s has not been formatted!", mJournalSystem));
}
//...
```

This is a raft journal log
```
bin/launch-process master -c
2022-04-27 09:21:54,626 ERROR AlluxioMaster - Fatal error: Failed to
create master process
java.lang.RuntimeException: java.lang.RuntimeException: Journal
alluxio.master.journal.raft.RaftJournalSystem@5c7fa833 has not been
formatted!
at
alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:125)
at
alluxio.master.FaultTolerantAlluxioMasterProcess.<init>(FaultTolerantAlluxioMasterProcess.java:61)
at
alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:471)
at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Journal
alluxio.master.journal.raft.RaftJournalSystem@5c7fa833 has not been
formatted!
at
alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:102)
... 3 more
```
The path of RaftJournal is not output in the log, which is not helpful
for finding bugs with the wrong Journal path

Example
```java
RaftJournalSystem{Journal Path=/mnt/share1/alluxio/journal, Local
Address=localhost:19200, State=STANDBY, Configuration
ClusterAddress=[localhost:19200], RaftGroup=null}
```


### Does this PR introduce any user facing changes?
No

pr-link: Alluxio/alluxio#15464
change-id: cid-0ab8db8e8ab0d58d390877de3d4905753c4e3106