Fix the button of logs tab page cannot work issue
### What changes are proposed in this pull request?

While using log web page to open log file, the end button or offset
input textbox didn’t work

### Why are the changes needed?

This is a simple bug, the `updateRequestParameter` was named to
`upateRequestParameter` in the browse.tsx and withFetchDataFromPath.tsx,
but named to `updateRequestParameter` in the `Logs.tsx`.

So I found error call stack in the browser console

```
Uncaught TypeError: a.props.updateRequestParameter is not a function
at t.<anonymous> (Logs.tsx:128)
at t.n.onClick (Button.js:52)
at Object.<anonymous> (react-dom.production.min.js:49)
at d (react-dom.production.min.js:69)
at react-dom.production.min.js:73
at T (react-dom.production.min.js:140)
at j (react-dom.production.min.js:169)
at k (react-dom.production.min.js:158)
at C (react-dom.production.min.js:232)
at On (react-dom.production.min.js:1718)
```

### Does this PR introduce any user facing changes?

No

pr-link: Alluxio/alluxio#13886
change-id: cid-42c7175277bcbf2afbf81fa3f4a71ff454e80e15