Throw exception when fail to create local cache
With this PR, a Presto query will fail with following error message when
the cache is unable to create:

```
Query 20200522_072107_00001_4hg9d failed: cannot create caching file
system
com.facebook.presto.spi.PrestoException: cannot create caching file
system
at
com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:80)
at
com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration$CachingJobConf.createFileSystem(HiveCachingHdfsConfiguration.java:104)
at
org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:56)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
at
com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
at
com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
at
com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
at
com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
at
com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:297)
at
com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:269)
at
com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:99)
at
com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:198)
at
com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
at
com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
at
com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
at
com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to create CacheManager
at
alluxio.client.file.cache.LocalCacheFileSystem.<init>(LocalCacheFileSystem.java:58)
at
com.facebook.presto.cache.alluxio.AlluxioCachingFileSystem$AlluxioCachingFileSystemInternal.initialize(AlluxioCachingFileSystem.java:109)
at
com.facebook.presto.cache.alluxio.AlluxioCachingFileSystem.initialize(AlluxioCachingFileSystem.java:60)
at
com.facebook.presto.cache.CacheFactory.createCachingFileSystem(CacheFactory.java:47)
at
com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:70)
... 19 more
Caused by: java.nio.file.AccessDeniedException:
/Users/binfan/tmp/test/LOCAL
at
sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at
sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
at java.nio.file.Files.createDirectory(Files.java:674)
at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
at java.nio.file.Files.createDirectories(Files.java:767)
at alluxio.client.file.cache.PageStore.initialize(PageStore.java:89)
at alluxio.client.file.cache.PageStore.create(PageStore.java:50)
at
alluxio.client.file.cache.LocalCacheManager.create(LocalCacheManager.java:156)
at alluxio.client.file.cache.CacheManager.create(CacheManager.java:31)
at
alluxio.client.file.cache.LocalCacheFileSystem.<init>(LocalCacheFileSystem.java:55)
... 23 more
```

pr-link: Alluxio/alluxio#11463
change-id: cid-5c7347086de05fb90e22023ec4a6250dcf9c3348