Fix double arg parsing in runTests
both
https://github.com/Alluxio/alluxio/pull/17170/files#diff-c80fd5152cf94b0cc483c26efb94f3946af189626fc4f10c0232bf968432078e
and https://github.com/Alluxio/alluxio/pull/17068/files introduced the
same change but in different lines so the merge was clean, but resulted
in parsing args twice

caught by running `bin/alluxio runTests --directory /path/to/dir` with
error msg:
```
error: Exception in thread "main"
com.beust.jcommander.ParameterException: Can only specify option
--directory once.
at
com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:240)
at
com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
at
com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
at com.beust.jcommander.JCommander.parse(JCommander.java:356)
at com.beust.jcommander.JCommander.parse(JCommander.java:335)
at alluxio.cli.TestRunner.main(TestRunner.java:110)
```

pr-link: Alluxio/alluxio#17199
change-id: cid-41ef7b12702f10c1e8b4cc729f99acc9e1b33753