Improve UfsIOBench and RpcBench command descriptions
### What changes are proposed in this pull request?

This change implements the missing description for `UfsIOBench` command
and improves descriptions in `RpcBench` children, conforming to the same
format.

Below is an example from `WorkerHeartbeatBench`. The rough structure is
description -> example -> options -> parse exception.

```
$ bin/alluxio runClass alluxio.stress.cli.WorkerHeartbeatBench foofoofoo
A benchmarking tool for the WorkerHeartbeat RPC.
The test will generate a specified number of blocks in the master
(without associated files). The test will also register the simulated
workers with the master. Then it will keep generating heartbeats with
the specified load and sending heartbeats to the master nonstop, until
the specified time has elapsed.

Example:
# 2 job workers will be chosen to run the benchmark
# Each job worker runs 3 threads each simulating one worker
# Each worker will have 3000 blocks on tier 0 and 10000 blocks on tier 1
# Keep sending heartbeats for 30s
$ bin/alluxio runClass alluxio.stress.cli.WorkerHeartbeatBench
--concurrency 3 \
--cluster --cluster-limit 2 --tiers "1000,1000,1000;5000,5000"
--duration 30s

Usage: WorkerHeartbeatBench [options]
Options:
--bench-timeout
The length of time to wait when finishing the benchmark. (10m 600s,
etc.)
Default: 20m
--cluster
If true, runs the benchmark via the job service cluster. Otherwise, runs
locally.
Default: false
--cluster-limit
If greater than 0, it will only run on that number of workers. If 0,
will run on all available cluster workers. If < 0, will run on the
workers from the end of the worker list. This flag is only used if
--cluster is enabled.
Default: 0
--concurrency
simulate this many clients/workers on one machine
Default: 2
--duration
The length of time to run the benchmark. (1m, 10m, 60s, 10000ms, etc.)
Default: 5s
-h, --help

--java-opt
The java options to add to the command line to for the task. This can be
repeated. The options must be quoted and prefixed with a space, to avoid
getting passed to the JVM. For example: --java-opt " -Xmx4g" --java-opt
" -Xms2g"
Default: []
--profile-agent
The path to the profile agent if one is available. Providing this will
enable a more detailed output.
Default: <empty string>
--tiers
The number of blocks in each storage dir and tier. List tiers in the
order of MEM, SSD and HDD separated by semicolon, list dirs inside each
tier separated by comma. Example: "100,200,300;1000,1500;2000"

com.beust.jcommander.ParameterException: Was passed main parameter
'foofoofoo' but no main parameter was defined in your arg class
at
com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
at com.beust.jcommander.JCommander.parse(JCommander.java:356)
at com.beust.jcommander.JCommander.parse(JCommander.java:335)
at alluxio.stress.cli.Benchmark.run(Benchmark.java:134)
at alluxio.stress.cli.Benchmark.mainInternal(Benchmark.java:90)
at
alluxio.stress.cli.WorkerHeartbeatBench.main(WorkerHeartbeatBench.java:192)
```

### Why are the changes needed?

See above

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
1. Command output

pr-link: Alluxio/alluxio#13936
change-id: cid-65dc8171f6b9fcca844ea050d42461c1ded70b7a