Fix IndexOutOfBoundsException on async cache
### What changes are proposed in this pull request?

Fix https://github.com/Alluxio/alluxio/issues/13828 and fix
https://github.com/Alluxio/alluxio/issues/13050

This patch will fix a miscaculation of block to async cache

In earlier Alluxio versions prior to
https://github.com/Alluxio/alluxio/pull/13064, users may see the
following errors:
```
2021-03-12 08:36:48,521 ERROR AlluxioFuseFileSystem - Failed to read
file=/data/0.5G_9.txt, offset=536862720, size=8192
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
```

After 13064, we will not see the error anymore but caching the last
block when fileSize happens on block size boundary will fail silently.

### Why are the changes needed?

Correct a bug when calculating the block id to async cache, when current
pos is fileSize which is a multiple of blockSize

### Does this PR introduce any user facing changes?

No

pr-link: Alluxio/alluxio#13845
change-id: cid-4c598c4f286a3da40e051cbac01e77818fb925a6