Fix jekyll installation in alluxio-maven dockerfiles
to address the following error

ERROR: Error installing jekyll:
The last version of public_suffix (< 6.0, >= 2.0.2) to support your Ruby
& RubyGems was 4.0.7. Try installing it with `gem install public_suffix
-v 4.0.7` and then running the current command again
public_suffix requires Ruby version >= 2.6. The current ruby version is
2.5.0

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
1. If you propose a new API, clarify the use case for a new API.
2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
1. change in user-facing APIs
2. addition or removal of property keys
3. webui

pr-link: Alluxio/alluxio#16080
change-id: cid-fddcf36d7bf559fcf8877cd337dd9d41ee22c600