Remove jetty all dependencies from hive metastore jar
Jetty all dependency is conflicted with the server jetty util dependency
which causes the master web UI to fail to start.
Error: Exception "java.lang.NoSuchMethodError:
org.eclipse.jetty.server.Server.<init>(Lorg/eclipse/jetty/util/thread/ThreadPool;)V",
Root Cause "null"
java.lang.NoSuchMethodError:
org.eclipse.jetty.server.Server.<init>(Lorg/eclipse/jetty/util/thread/ThreadPool;

pr-link: Alluxio/alluxio#11497
change-id: cid-7683bfaa7c38e17c8a15a4bab80846b6c538522a