Fix helm-chart master statefulset.yaml env space Indent
If `env` is set for the master, the space indentation of the current
helm template is not aligned with the context. So that helm will report
error like this:
```
Error: YAML parse error on alluxio/templates/master/statefulset.yaml:
error converting YAML to JSON: yaml: line 81: did not find expected key
```

This PR try to fix the space Indent in `master/statefulset.yaml`

pr-link: Alluxio/alluxio#13180
change-id: cid-561255cf776e7efac98b581cc83c74243ce572b6