Move container level securityContext to pod level
When using Alluxio worker in Kubernetes, the Daemonset template mounts
the directory `/opt/domain`. However previously when doing so the worker
would crash with the following error:

```
2021-03-13 00:32:55,274 INFO GrpcDataServer - Alluxio worker gRPC server
started, listening on /0.0.0.0:29999
2021-03-13 00:32:55,275 INFO AlluxioWorkerProcess - Domain socket data
server is enabled at /opt/domain/b7f2d035-e081-4a55-a9d3-a87351d8daad.
2021-03-13 00:32:55,281 WARN RetryUtils - Failed to Starting gRPC server
(attempt 1): java.io.IOException: Failed to bind
2021-03-13 00:32:55,482 WARN RetryUtils - Failed to Starting gRPC server
(attempt 2): java.io.IOException: Failed to bind
2021-03-13 00:32:55,883 WARN RetryUtils - Failed to Starting gRPC server
(attempt 3): java.io.IOException: Failed to bind
2021-03-13 00:32:56,384 WARN RetryUtils - Failed to Starting gRPC server
(attempt 4): java.io.IOException: Failed to bind
2021-03-13 00:32:56,885 WARN RetryUtils - Failed to Starting gRPC server
(attempt 5): java.io.IOException: Failed to bind
2021-03-13 00:32:57,386 WARN RetryUtils - Failed to Starting gRPC server
(attempt 6): java.io.IOException: Failed to bind
2021-03-13 00:32:57,387 ERROR GrpcDataServer - Alluxio worker gRPC
server failed to start on
/opt/domain/b7f2d035-e081-4a55-a9d3-a87351d8daad
java.io.IOException: Failed to bind
at io.grpc.netty.NettyServer.start(NettyServer.java:252)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:184)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
at alluxio.grpc.GrpcServer.lambda$start$0(GrpcServer.java:77)
at alluxio.retry.RetryUtils.retry(RetryUtils.java:39)
at alluxio.grpc.GrpcServer.start(GrpcServer.java:77)
at alluxio.worker.grpc.GrpcDataServer.<init>(GrpcDataServer.java:107)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at alluxio.util.CommonUtils.createNewClassInstance(CommonUtils.java:285)
at alluxio.worker.DataServer$Factory.create(DataServer.java:47)
at
alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:162)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:46)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:72)
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..)
failed: Permission denied
2021-03-13 00:32:57,391 ERROR AlluxioWorker - Fatal error: Failed to
create worker process
java.lang.RuntimeException: java.lang.RuntimeException:
java.lang.RuntimeException: Alluxio worker gRPC server failed to start
on /opt/domain/b7f2d035-e081-4a55-a9d3-a87351d8daad
at
alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:168)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:46)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:72)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException:
Alluxio worker gRPC server failed to start on
/opt/domain/b7f2d035-e081-4a55-a9d3-a87351d8daad
at alluxio.util.CommonUtils.createNewClassInstance(CommonUtils.java:287)
at alluxio.worker.DataServer$Factory.create(DataServer.java:47)
at
alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:162)
... 3 more
Caused by: java.lang.RuntimeException: Alluxio worker gRPC server failed
to start on /opt/domain/b7f2d035-e081-4a55-a9d3-a87351d8daad
at alluxio.worker.grpc.GrpcDataServer.<init>(GrpcDataServer.java:112)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at alluxio.util.CommonUtils.createNewClassInstance(CommonUtils.java:285)
... 5 more
Caused by: java.io.IOException: Failed to bind
at io.grpc.netty.NettyServer.start(NettyServer.java:252)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:184)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
at alluxio.grpc.GrpcServer.lambda$start$0(GrpcServer.java:77)
at alluxio.retry.RetryUtils.retry(RetryUtils.java:39)
at alluxio.grpc.GrpcServer.start(GrpcServer.java:77)
at alluxio.worker.grpc.GrpcDataServer.<init>(GrpcDataServer.java:107)
... 10 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..)
failed: Permission denied
```

Upon investigating the `alluxio-worker` container in my Alluxio worker
pod, we see that `/opt/domain` gets mounted with `root:root` as the
user:group:
```
[kubernetes@ip-172-31-76-132 shortcircuit]$ kubectl exec -it
alluxio-worker-b28rm -c alluxio-job-worker /bin/bash
bash-4.4$ ls -l /opt
total 4
lrwxrwxrwx 1 alluxio alluxio 13 Mar 5 20:17 alluxio -> alluxio-2.5.0
drwxr-xr-x 1 alluxio alluxio 30 Mar 5 19:52 alluxio-2.5.0
drwxr-xr-x 3 root root 4096 Mar 5 20:18 arthas
drwxr-xr-x 3 root root 104 Mar 5 20:18 async-profiler
drwxr-xr-x 2 root root 6 Mar 12 23:51 domain
```

According to the [Kubernetes SecurityContext
docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
using `fsGroup` should have been sufficient but it appears that the
volume is still being mounted with the default user:group of root:root.

This PR adds `runAsRoot` and `runAsGroup` to the top-level
`SecurityContext` to enforce the volume to be mounted with the correct
user:group permissions.

## Alternative solution
A more hacky approach which is [commonly
suggested](https://serverfault.com/a/907160) is to use an
`initContainer` to `chown` the volume mount directly as this will
persist during the Pod's lifecycle.

## Testing
Both approaches have been tested by @ZhuTopher in a standalone K8s
deployment on EC2. Additional details about the setup are available
[here](https://github.com/Alluxio/alluxio/issues/13022#issuecomment-797840435)

pr-link: Alluxio/alluxio#13061
change-id: cid-1668f1734b769f9966ea3754750503862feacecb