Fix flaky BlockMasterMetricsTest.testSize
### What changes are proposed in this pull request?

Fix flaky `BlockMasterMetricsTest.testSize`, e.g.
https://github.com/Alluxio/alluxio/runs/4037547872?check_suite_focus=true

```console
Error: 9.386 [ERROR]
alluxio.master.block.BlockMasterMetricsTest.testSize Time elapsed: 0.002
s <<< FAILURE!
java.lang.AssertionError: expected:<100> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at
alluxio.master.block.BlockMasterMetricsTest.testSize(BlockMasterMetricsTest.java:83)
```

### Does this PR introduce any user facing changes?

No.

pr-link: Alluxio/alluxio#14339
change-id: cid-8ad79336b51a71f6fb7f60a133db9da9327e38b7