Disable delegation on alluxio-site.properties.template
As https://github.com/Alluxio/alluxio/pull/3451 discussed, we should disable the delegation. In addition, I got a timeout issue when running MapReduce with the use of delegation.

```Java
INFO mapreduce.Job: Task Id : attempt_1465596856169_0003_m_000147_0, Status : FAILED
Error: java.io.IOException: java.util.concurrent.TimeoutException: Timeout waiting for task.
  at alluxio.client.netty.NettyUnderFileSystemFileWriter.write(NettyUnderFileSystemFileWriter.java:103)
  at alluxio.client.file.UnderFileSystemFileOutStream.writeToWorker(UnderFileSystemFileOutStream.java:161)
  at alluxio.client.file.UnderFileSystemFileOutStream.flush(UnderFileSystemFileOutStream.java:85)
  at alluxio.client.file.UnderFileSystemFileOutStream.close(UnderFileSystemFileOutStream.java:75)
  at alluxio.client.file.FileOutStream.close(FileOutStream.java:157)
  at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
  at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
  at org.apache.hadoop.io.SequenceFile$Writer.close(SequenceFile.java:1349)
  at org.apache.hadoop.mapred.SequenceFileOutputFormat$1.close(SequenceFileOutputFormat.java:79)
  at org.apache.hadoop.mapred.MapTask$DirectMapOutputCollector.close(MapTask.java:844)
  at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
  at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
  at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:422)
  at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
  at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
  at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
  at alluxio.client.netty.SingleResponseListener.get(SingleResponseListener.java:65)
  at alluxio.client.netty.NettyUnderFileSystemFileWriter.write(NettyUnderFileSystemFileWriter.java:81)
  ... 16 more
```