Fix NoClassDefFoundError #13527
Fix NoClassDefFoundError when dfs.namenode.kerberos.principal.pattern is
set #13527
When ufs is kerberosed HDFS and dfs.namenode.kerberos.principal.pattern
is set in hdfs-site.xml, the Alluxio couldn't set up IO streams with
HDFS. The cause is java.lang.NoClassDefFoundError:
alluxio/shaded/hdfs/com/google/re2j/PatternSyntaxException.
Shaded the dependency com.google.re2j in alluxio-shaded-hadoop and
alluxio-shaded-ozone modules.

pr-link: Alluxio/alluxio#13528
change-id: cid-475ed6964eec2e570f3f1ad894a41fc9a3754921