Fix standby master don't remove syncPoint correctly issue
### What changes are proposed in this pull request?

When unmounting the mount point, make the deletion of syncPoint be applied to the standby master through journal.

### Why are the changes needed?
If use `NOOP` journal, standby master will not remove the syncPoint, then if the standby become leader, if will crash and throw exception

```
2023-11-07 20:48:30,700 ERROR [main](ProcessUtils.java:76) - Uncaught exception while running Alluxio master @xx.xxx.xxx.xxx:xxxx, stopping it and exiting. Exception "java.lang.UnsupportedOperationException: Active Sync is not supported on this UFS type: local", Root Cause "java.lang.UnsupportedOperationException: Active Sync is not supported on this UFS type: local"
java.lang.UnsupportedOperationException: Active Sync is not supported on this UFS type: local
	at alluxio.master.file.activesync.ActiveSyncManager.start(ActiveSyncManager.java:209)
	at alluxio.master.file.DefaultFileSystemMaster.start(DefaultFileSystemMaster.java:826)
	at alluxio.master.file.TxFileSystemMaster.start(TxFileSystemMaster.java:285)
	at alluxio.master.file.TxFileSystemMaster.start(TxFileSystemMaster.java:167)
	at alluxio.Registry.start(Registry.java:129)
	at alluxio.master.AlluxioMasterProcess.startMasterComponents(AlluxioMasterProcess.java:453)
	at alluxio.master.AlluxioMasterProcess.promote(AlluxioMasterProcess.java:362)
	at alluxio.master.AlluxioMasterProcess.start(AlluxioMasterProcess.java:278)
	at alluxio.ProcessUtils.run(ProcessUtils.java:69)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:55)
```

### Does this PR introduce any user facing changes?
No

			pr-link: Alluxio/alluxio#18415
			change-id: cid-7312777c7f346c29d698f8feed25c60d3f067358