Fix incorrect directory when mounting & formatting master journal volume
### What changes are proposed in this pull request?

This PR simply adds the `alluxio-config` ConfigMap to the
`initContainer` which is launched to format the master journal.
Furthermore, it also uses the value set in `.Values.journal.folder` as
the mount directory for journal PVs.

### Why are the changes needed?

Without these changes, the PV intended as the Alluxio master journal
would always be mounted under `/journal`. This would be completely
ignored if the user changed `.Values.journal.folder` to anything other
than `/journal`.

Furthermore, attempting to use the `initContainer` to run the journal
format job would cause the journal to be mounted to the [Alluxio default
value](https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html?q=alluxio.master.journal.folder)
`alluxio.master.journal.folder=${alluxio.work.dir}/journal`.

For example with the following journal values:
```
journal:
type: "EMBEDDED"
folder: "/tmp/journal"
format:
runFormat: true
```

Before:
```
$ kubectl logs -f alluxio-master-0 -c journal-format
Formatting Alluxio Master @
alluxio-master-0.alluxio-master.default.svc.cluster.local
2022-02-23 19:25:10,778 INFO Format - Formatting master journal:
/opt/alluxio-2.8.0-SNAPSHOT/journal/
2022-02-23 19:25:10,841 INFO Format - Formatting complete

$ kubectl logs -f alluxio-master-0 -c alluxio-master
2022-02-23 19:31:10,679 ERROR AlluxioMaster - Fatal error: Failed to
create master process
java.lang.RuntimeException: java.lang.RuntimeException: Journal
alluxio.master.journal.raft.RaftJournalSystem@1810399e has not been
formatted!
at
alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:122)
at
alluxio.master.FaultTolerantAlluxioMasterProcess.<init>(FaultTolerantAlluxioMasterProcess.java:61)
at
alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:467)
at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Journal
alluxio.master.journal.raft.RaftJournalSystem@1810399e has not been
formatted!
at
alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:101)
... 3 more
```

After:
```
$ kubectl logs -f alluxio-master-0 -c journal-format
Formatting Alluxio Master @
alluxio-master-0.alluxio-master.default.svc.cluster.local
2022-02-23 19:38:55,662 INFO Format - Formatting master journal:
/tmp/journal/
2022-02-23 19:38:55,716 INFO Format - Formatting complete

$ kubectl logs -f alluxio-master-0 -c alluxio-master
...
2022-02-23 19:39:15,778 INFO FaultTolerantAlluxioMasterProcess - Primary
started
2022-02-23 19:39:15,778 INFO DefaultSafeModeManager - Rpc server
started, waiting 5000ms for workers to register
2022-02-23 19:39:15,778 INFO AlluxioMasterProcess - gRPC server
listening on: 0.0.0.0:19998
2022-02-23 19:39:15,779 INFO AlluxioMasterProcess - Alluxio master
version 2.8.0-SNAPSHOT started (gained leadership).
bindAddress=0.0.0.0/0.0.0.0:19998, connectAddress=10.244.1.11:19998,
webAddress=/0.0.0.0:19999
```

### Does this PR introduce any user facing changes?

One user-facing value changes:
- `journal.ufsType` option "HDFS" was semantically changed to
`"non-local"`
- The prior value of "HDFS" will still be accepted and behave as
expected. This value change is purely for clarity and posterity.
- The k8s docs were updated to reflect this

Some comments were added to the entirety of the `journal` section of
`values.yaml` for clarity.

pr-link: Alluxio/alluxio#15045
change-id: cid-0649a2aba0b87996a510ff629c9c600b45388d64