Fix NoClassDefFoundError when dfs.namenode.kerberos.principal.pattern is set #13527
When ufs is kerberosed HDFS and dfs.namenode.kerberos.principal.pattern is set in hdfs-site.xml, the Alluxio couldn't set up IO streams with HDFS. The cause is java.lang.NoClassDefFoundError: alluxio/shaded/hdfs/com/google/re2j/PatternSyntaxException.
Shaded the dependency com.google.re2j in alluxio-shaded-hadoop and alluxio-shaded-ozone modules.