Improve tiered storage related logging
- add info logging for each storage dir on init, which will be very
useful for debugging worker tiered storage
- prevent duplicated error info in worker.log as seen in the following.
The same error caused two logging messages, one in tiered block store
and on in blockwritehandler. This is because previous code catches an
exception from allocator, log it and returns null, then in its caller,
based on null, another exception is created and thrown. This PR simply
keep the original exception from allocator.
- remove `freeSpace` from `BlockWorker` interface as no external callers
depend on this

```
021-03-23 03:39:52,791 ERROR TieredBlockStore - Allocation failure.
Options: AllocateOptions{Location=BlockStoreLocation{TierAlias=MEM,
DirIndex=0, MediumType=MEM}, Size=335544320, ForceLocation=true,
EvictionAllowed=true, UseReservedSpace=false}. Error:
alluxio.exception.WorkerOutOfSpaceException: Failed to free 335544320
bytes space at location MEM. Min contiguous requested: 335544320, Min
available requested: 335544320, Blocks iterated: 2, Blocks removed: 2,
Space freed: 268435456
at
alluxio.worker.block.TieredBlockStore.freeSpaceInternal(TieredBlockStore.java:825)
at
alluxio.worker.block.TieredBlockStore.freeSpace(TieredBlockStore.java:455)
at
alluxio.worker.block.TieredBlockStore.allocateSpace(TieredBlockStore.java:651)
at
alluxio.worker.block.TieredBlockStore.requestSpace(TieredBlockStore.java:318)
at
alluxio.worker.block.DefaultBlockWorker.requestSpace(DefaultBlockWorker.java:483)
at
alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:132)
at
alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
at
alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
at
alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
at
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at
alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2021-03-23 03:39:52,796 ERROR AbstractWriteHandler - Failed to write
data for request BlockWriteRequest{id=3489660931,
sessionId=4499861889621204869, tier=0, createUfsBlockOptions=null}
alluxio.exception.WorkerOutOfSpaceException: Can't reserve more space
for block: 3489660931 under session: 4499861889621204869.
at
alluxio.worker.block.TieredBlockStore.requestSpace(TieredBlockStore.java:321)
at
alluxio.worker.block.DefaultBlockWorker.requestSpace(DefaultBlockWorker.java:483)
at
alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:132)
at
alluxio.worker.grpc.BlockWriteHandler.writeBuf(BlockWriteHandler.java:36)
at
alluxio.worker.grpc.AbstractWriteHandler.writeData(AbstractWriteHandler.java:274)
at
alluxio.worker.grpc.AbstractWriteHandler.lambda$writeDataMessage$1(AbstractWriteHandler.java:175)
at
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at
alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:91)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

pr-link: Alluxio/alluxio#13154
change-id: cid-6412a80556e8757835940f8c4b3853c5fa39bd37