Move raft journal to an isolated directory
Master log shows the following error:

```
"2020-09-14 17:19:37,127 WARN RaftServerProxy -
FaultToleranceScaleEmbeddedJournalR-masters-1_19200: Failed to
initialize the group directory /tmp/alluxio/journal/JobJournal. Ignoring
it
java.lang.IllegalArgumentException: Invalid UUID string: JobJournal
at java.util.UUID.fromString(UUID.java:194)
at
org.apache.ratis.server.impl.RaftServerProxy.lambda$null$0(RaftServerProxy.java:197)"
```

It's because Ratis scans all directories under the configured path now
and calls out the ones that are not named as a raft group id. Since we
have `JobJournal` as a sub directory of the master journal directory, it
is detected by Ratis which will log an error. This change addresses this
issue by moving Ratis journal path to be one level deeper so it does not
scan the parent directory of `JobJournal` directory.

pr-link: Alluxio/alluxio#12217
change-id: cid-1e4c82669c8978a4425a9b8e7645af4ac6720fc9